
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://service/")
public interface WebService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "transWords", targetNamespace = "http://service/", className = "client.TransWords")
	@ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://service/", className = "client.TransWordsResponse")
	public String transWords(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
